version: '3'

networks:
  token-cc-net:
    external: true

services:
  goinitus:
    image: goledger/cc-webclient:latest
    container_name: goinitus
    ports:
      - "8080:80"
    networks:
      - token-cc-net
